import Storage, { KEYS } from './localStorage';
import { generateId } from './quizUtils';

const demoUsers = [
  {
    id: 'u1',
    name: 'John Student',
    email: 'student@example.com',
    password: 'student123',
    role: 'student',
    createdAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'u2',
    name: 'Jane Teacher',
    email: 'teacher@example.com',
    password: 'teacher123',
    role: 'teacher',
    createdAt: '2025-01-10T08:00:00.000Z',
  },
  {
    id: 'u3',
    name: 'Alice Student',
    email: 'alice@example.com',
    password: 'alice123',
    role: 'student',
    createdAt: '2025-02-01T09:00:00.000Z',
  },
  {
    id: 'u4',
    name: 'Bob Student',
    email: 'bob@example.com',
    password: 'bob123',
    role: 'student',
    createdAt: '2025-02-10T11:00:00.000Z',
  },
];

const demoQuizzes = [
  {
    id: 'q1',
    title: 'JavaScript Fundamentals',
    description: 'Test your knowledge of core JavaScript concepts including variables, functions, and control flow.',
    category: 'JavaScript',
    difficulty: 'Medium',
    timeLimit: 20,
    passingPercentage: 50,
    status: 'Published',
    createdBy: 'u2',
    createdAt: '2025-03-01T10:00:00.000Z',
    questions: [
      {
        id: 'q1ques1',
        text: 'What is the output of typeof null?',
        options: ['"null"', '"undefined"', '"object"', '"boolean"'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'In JavaScript, typeof null returns "object", which is a well-known bug in the language.',
      },
      {
        id: 'q1ques2',
        text: 'Which keyword is used to declare a constant in JavaScript?',
        options: ['var', 'let', 'const', 'define'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The "const" keyword is used to declare a constant that cannot be reassigned.',
      },
      {
        id: 'q1ques3',
        text: 'What does "===" operator check?',
        options: ['Value only', 'Type only', 'Value and type', 'Reference'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The strict equality operator (===) checks both value and type without type coercion.',
      },
      {
        id: 'q1ques4',
        text: 'Which array method adds an element to the end?',
        options: ['unshift()', 'push()', 'pop()', 'shift()'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The push() method adds one or more elements to the end of an array.',
      },
      {
        id: 'q1ques5',
        text: 'What is a closure in JavaScript?',
        options: [
          'A way to close browser windows',
          'A function that has access to its outer scope variables',
          'A method to end loops',
          'A type of error',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'A closure is a function that retains access to variables from its outer (enclosing) function scope even after the outer function has returned.',
      },
      {
        id: 'q1ques6',
        text: 'What will [1,2,3].map(x => x * 2) return?',
        options: ['[1,2,3]', '[2,4,6]', '[1,4,9]', 'undefined'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The map method creates a new array by applying a function to each element.',
      },
      {
        id: 'q1ques7',
        text: 'Which method is used to parse a JSON string?',
        options: ['JSON.parse()', 'JSON.stringify()', 'JSON.convert()', 'JSON.decode()'],
        correctAnswer: 0,
        marks: 1,
        explanation: 'JSON.parse() is used to parse a JSON string and construct the JavaScript object.',
      },
      {
        id: 'q1ques8',
        text: 'What is the result of 0.1 + 0.2 === 0.3?',
        options: ['true', 'false', 'undefined', 'Error'],
        correctAnswer: 1,
        marks: 2,
        explanation: 'Due to floating-point precision issues, 0.1 + 0.2 equals 0.30000000000000004, not 0.3.',
      },
      {
        id: 'q1ques9',
        text: 'What does the "this" keyword refer to in a regular function?',
        options: [
          'The function itself',
          'The global object (in non-strict mode)',
          'The parent function',
          'Undefined always',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'In a regular function, "this" refers to the global object in non-strict mode, and undefined in strict mode.',
      },
      {
        id: 'q1ques10',
        text: 'Which of the following is a valid way to create an array?',
        options: [
          'let arr = new Array(1, 2, 3)',
          'let arr = [1, 2, 3]',
          'let arr = Array.of(1, 2, 3)',
          'All of the above',
        ],
        correctAnswer: 3,
        marks: 1,
        explanation: 'All three methods are valid ways to create arrays in JavaScript.',
      },
    ],
  },
  {
    id: 'q2',
    title: 'Python Basics',
    description: 'Test your understanding of Python fundamentals including syntax, data types, and basic operations.',
    category: 'Python',
    difficulty: 'Easy',
    timeLimit: 15,
    passingPercentage: 60,
    status: 'Published',
    createdBy: 'u2',
    createdAt: '2025-03-05T14:00:00.000Z',
    questions: [
      {
        id: 'q2ques1',
        text: 'What is the output of print(type(5))?',
        options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "<class 'number'>"],
        correctAnswer: 0,
        marks: 1,
        explanation: '5 is an integer in Python, so type(5) returns <class "int">.',
      },
      {
        id: 'q2ques2',
        text: 'Which keyword is used to define a function in Python?',
        options: ['function', 'func', 'def', 'define'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The "def" keyword is used to define a function in Python.',
      },
      {
        id: 'q2ques3',
        text: 'What is the correct file extension for Python files?',
        options: ['.python', '.py', '.pt', '.pyt'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'Python files use the .py extension.',
      },
      {
        id: 'q2ques4',
        text: 'How do you create a list in Python?',
        options: ['{}', '()', '[]', '<>'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'Square brackets [] are used to create lists in Python.',
      },
      {
        id: 'q2ques5',
        text: 'What is the output of print(2 ** 3)?',
        options: ['6', '8', '5', '23'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The ** operator is the exponentiation operator. 2 ** 3 = 2^3 = 8.',
      },
      {
        id: 'q2ques6',
        text: 'Which of the following is immutable in Python?',
        options: ['List', 'Dictionary', 'Set', 'Tuple'],
        correctAnswer: 3,
        marks: 1,
        explanation: 'Tuples are immutable in Python, meaning their elements cannot be changed after creation.',
      },
      {
        id: 'q2ques7',
        text: 'What does len() function do?',
        options: ['Returns the length of an object', 'Converts to lowercase', 'Rounds a number', 'Sorts a list'],
        correctAnswer: 0,
        marks: 1,
        explanation: 'The len() function returns the number of items in an object.',
      },
      {
        id: 'q2ques8',
        text: 'How do you start a comment in Python?',
        options: ['//', '/*', '#', '--'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The # symbol is used to start a single-line comment in Python.',
      },
      {
        id: 'q2ques9',
        text: 'What is the output of print("Hello"[0])?',
        options: ['H', 'e', 'Hello', '0'],
        correctAnswer: 0,
        marks: 1,
        explanation: 'String indexing starts at 0, so "Hello"[0] returns "H".',
      },
      {
        id: 'q2ques10',
        text: 'Which method adds an element to the end of a list?',
        options: ['add()', 'append()', 'insert()', 'push()'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The append() method adds an element to the end of a list.',
      },
    ],
  },
  {
    id: 'q3',
    title: 'React.js Essentials',
    description: 'Challenge yourself on React components, hooks, state management, and JSX fundamentals.',
    category: 'React.js',
    difficulty: 'Hard',
    timeLimit: 25,
    passingPercentage: 50,
    status: 'Published',
    createdBy: 'u2',
    createdAt: '2025-03-10T09:00:00.000Z',
    questions: [
      {
        id: 'q3ques1',
        text: 'What hook is used for side effects in React?',
        options: ['useState', 'useEffect', 'useContext', 'useReducer'],
        correctAnswer: 1,
        marks: 2,
        explanation: 'useEffect is used for side effects like data fetching, subscriptions, and DOM manipulation.',
      },
      {
        id: 'q3ques2',
        text: 'What is JSX?',
        options: [
          'A JavaScript XML parser',
          'A syntax extension for JavaScript',
          'A new programming language',
          'A CSS preprocessor',
        ],
        correctAnswer: 1,
        marks: 1,
        explanation: 'JSX is a syntax extension for JavaScript that looks similar to HTML and is used in React.',
      },
      {
        id: 'q3ques3',
        text: 'How do you pass data from parent to child in React?',
        options: ['State', 'Props', 'Context only', 'Redux only'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'Props (properties) are used to pass data from parent to child components.',
      },
      {
        id: 'q3ques4',
        text: 'What is the virtual DOM?',
        options: [
          'A direct copy of the real DOM',
          'A lightweight copy of the real DOM',
          'A browser API',
          'A database for React',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'The virtual DOM is a lightweight JavaScript representation of the real DOM used for efficient updates.',
      },
      {
        id: 'q3ques5',
        text: 'Which hook manages local component state?',
        options: ['useEffect', 'useRef', 'useState', 'useMemo'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'useState is the primary hook for managing local state in functional components.',
      },
      {
        id: 'q3ques6',
        text: 'What is the purpose of React keys?',
        options: [
          'To style components',
          'To help React identify which items have changed',
          'To create CSS animations',
          'To handle form inputs',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'Keys help React identify which items in a list have changed, added, or removed for efficient re-rendering.',
      },
      {
        id: 'q3ques7',
        text: 'What does useCallback do?',
        options: [
          'Caches a function between re-renders',
          'Calls a function on mount',
          'Creates a new function each render',
          'Removes a callback',
        ],
        correctAnswer: 0,
        marks: 2,
        explanation: 'useCallback returns a memoized callback that only changes if its dependencies change.',
      },
      {
        id: 'q3ques8',
        text: 'Which method is used to prevent unnecessary re-renders?',
        options: ['React.memo', 'React.lazy', 'React.freeze', 'React.cache'],
        correctAnswer: 0,
        marks: 2,
        explanation: 'React.memo wraps a component to skip re-rendering if its props haven\'t changed.',
      },
      {
        id: 'q3ques9',
        text: 'What is a controlled component?',
        options: [
          'A component controlled by the DOM',
          'A component whose value is driven by React state',
          'A component with no state',
          'A component that controls other components',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'A controlled component has its form data handled by React state rather than the DOM.',
      },
      {
        id: 'q3ques10',
        text: 'What does useRef return?',
        options: [
          'A new DOM element',
          'A mutable ref object with a .current property',
          'A state variable',
          'A promise',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'useRef returns a mutable ref object whose .current property persists across renders.',
      },
    ],
  },
  {
    id: 'q4',
    title: 'Data Structures & Algorithms',
    description: 'Test your knowledge of fundamental data structures and algorithmic concepts.',
    category: 'Data Structures',
    difficulty: 'Hard',
    timeLimit: 30,
    passingPercentage: 40,
    status: 'Published',
    createdBy: 'u2',
    createdAt: '2025-03-15T11:00:00.000Z',
    questions: [
      {
        id: 'q4ques1',
        text: 'What is the time complexity of binary search?',
        options: ['O(n)', 'O(log n)', 'O(n^2)', 'O(1)'],
        correctAnswer: 1,
        marks: 2,
        explanation: 'Binary search halves the search space each step, giving O(log n) time complexity.',
      },
      {
        id: 'q4ques2',
        text: 'Which data structure uses LIFO (Last In, First Out)?',
        options: ['Queue', 'Stack', 'Array', 'Linked List'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'A stack follows the LIFO principle where the last element added is the first to be removed.',
      },
      {
        id: 'q4ques3',
        text: 'What is a hash table?',
        options: [
          'A sorted array',
          'A data structure that maps keys to values',
          'A type of tree',
          'A linear data structure',
        ],
        correctAnswer: 1,
        marks: 2,
        explanation: 'A hash table uses a hash function to map keys to values, providing O(1) average lookup.',
      },
      {
        id: 'q4ques4',
        text: 'What is the average case time complexity of quicksort?',
        options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
        correctAnswer: 1,
        marks: 2,
        explanation: 'Quicksort has an average time complexity of O(n log n) due to its divide-and-conquer approach.',
      },
      {
        id: 'q4ques5',
        text: 'Which traversal visits the root first in a binary tree?',
        options: ['In-order', 'Post-order', 'Pre-order', 'Level-order'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'Pre-order traversal visits the root node first, then the left subtree, then the right subtree.',
      },
      {
        id: 'q4ques6',
        text: 'What is the space complexity of merge sort?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
        correctAnswer: 2,
        marks: 2,
        explanation: 'Merge sort requires O(n) extra space for the temporary arrays used during merging.',
      },
      {
        id: 'q4ques7',
        text: 'What is a circular queue?',
        options: [
          'A queue that loops back to the beginning',
          'A queue with only one element',
          'A queue with no elements',
          'A priority queue',
        ],
        correctAnswer: 0,
        marks: 1,
        explanation: 'A circular queue wraps around when it reaches the end, efficiently using the available space.',
      },
      {
        id: 'q4ques8',
        text: 'Which data structure is best for implementing a priority queue?',
        options: ['Array', 'Linked List', 'Heap', 'Stack'],
        correctAnswer: 2,
        marks: 2,
        explanation: 'A heap (binary heap) is the most efficient data structure for implementing a priority queue.',
      },
    ],
  },
  {
    id: 'q5',
    title: 'HTML & CSS Quiz',
    description: 'Test your knowledge of HTML5 and CSS3 including semantic elements, layouts, and responsive design.',
    category: 'HTML & CSS',
    difficulty: 'Easy',
    timeLimit: 15,
    passingPercentage: 60,
    status: 'Published',
    createdBy: 'u2',
    createdAt: '2025-03-20T13:00:00.000Z',
    questions: [
      {
        id: 'q5ques1',
        text: 'What does HTML stand for?',
        options: [
          'Hyper Text Markup Language',
          'High Tech Modern Language',
          'Hyper Transfer Markup Language',
          'Home Tool Markup Language',
        ],
        correctAnswer: 0,
        marks: 1,
        explanation: 'HTML stands for HyperText Markup Language, the standard language for web pages.',
      },
      {
        id: 'q5ques2',
        text: 'Which CSS property is used to change text color?',
        options: ['font-color', 'text-color', 'color', 'foreground'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The "color" property in CSS is used to set the text color of an element.',
      },
      {
        id: 'q5ques3',
        text: 'Which HTML tag is used for the largest heading?',
        options: ['<heading>', '<h6>', '<h1>', '<head>'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The <h1> tag defines the largest and most important heading in HTML.',
      },
      {
        id: 'q5ques4',
        text: 'What does CSS stand for?',
        options: [
          'Cascading Style Sheets',
          'Computer Style Sheets',
          'Creative Style System',
          'Colorful Style Sheets',
        ],
        correctAnswer: 0,
        marks: 1,
        explanation: 'CSS stands for Cascading Style Sheets, used to style HTML elements.',
      },
      {
        id: 'q5ques5',
        text: 'Which property is used for CSS Flexbox layout?',
        options: ['display: block', 'display: flex', 'display: inline', 'display: table'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'Setting display: flex on a container enables Flexbox layout for its children.',
      },
      {
        id: 'q5ques6',
        text: 'Which HTML5 element is used for navigation?',
        options: ['<navigation>', '<nav>', '<menu>', '<links>'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The <nav> element represents a section of navigation links.',
      },
      {
        id: 'q5ques7',
        text: 'What is the default position value in CSS?',
        options: ['absolute', 'relative', 'static', 'fixed'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'The default position value is "static", meaning the element follows normal document flow.',
      },
      {
        id: 'q5ques8',
        text: 'Which CSS unit is relative to the parent element?',
        options: ['px', 'em', 'pt', 'cm'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The "em" unit is relative to the font-size of the parent element.',
      },
    ],
  },
  {
    id: 'q6',
    title: 'Java Programming',
    description: 'Test your Java knowledge covering OOP concepts, collections, and core APIs.',
    category: 'Java',
    difficulty: 'Medium',
    timeLimit: 20,
    passingPercentage: 50,
    status: 'Draft',
    createdBy: 'u2',
    createdAt: '2025-03-25T16:00:00.000Z',
    questions: [
      {
        id: 'q6ques1',
        text: 'Which keyword is used to inherit a class in Java?',
        options: ['implements', 'extends', 'inherits', 'super'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The "extends" keyword is used for class inheritance in Java.',
      },
      {
        id: 'q6ques2',
        text: 'What is the size of an int in Java?',
        options: ['2 bytes', '4 bytes', '8 bytes', '16 bytes'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'In Java, an int is always 4 bytes (32 bits) regardless of the platform.',
      },
      {
        id: 'q6ques3',
        text: 'Which collection class allows duplicate elements?',
        options: ['Set', 'Map', 'List', 'None of these'],
        correctAnswer: 2,
        marks: 1,
        explanation: 'List implementations (like ArrayList, LinkedList) allow duplicate elements.',
      },
      {
        id: 'q6ques4',
        text: 'What is the default value of a boolean in Java?',
        options: ['true', 'false', 'null', '0'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The default value of a boolean field in Java is false.',
      },
      {
        id: 'q6ques5',
        text: 'Which method is the entry point of a Java program?',
        options: ['start()', 'main()', 'init()', 'run()'],
        correctAnswer: 1,
        marks: 1,
        explanation: 'The main() method is the entry point for any Java application.',
      },
    ],
  },
];

const demoAttempts = [
  {
    id: 'a1',
    userId: 'u1',
    quizId: 'q1',
    answers: { 'q1ques1': 2, 'q1ques2': 2, 'q1ques3': 2, 'q1ques4': 1, 'q1ques5': 1, 'q1ques6': 1, 'q1ques7': 0, 'q1ques8': 1, 'q1ques9': 1, 'q1ques10': 3 },
    score: 9,
    totalMarks: 12,
    percentage: 75,
    passed: true,
    timeTaken: 600,
    startedAt: '2025-04-01T10:00:00.000Z',
    submittedAt: '2025-04-01T10:10:00.000Z',
  },
  {
    id: 'a2',
    userId: 'u1',
    quizId: 'q2',
    answers: { 'q2ques1': 0, 'q2ques2': 2, 'q2ques3': 1, 'q2ques4': 2, 'q2ques5': 1, 'q2ques6': 3, 'q2ques7': 0, 'q2ques8': 2, 'q2ques9': 0, 'q2ques10': 1 },
    score: 10,
    totalMarks: 10,
    percentage: 100,
    passed: true,
    timeTaken: 420,
    startedAt: '2025-04-05T14:00:00.000Z',
    submittedAt: '2025-04-05T14:07:00.000Z',
  },
  {
    id: 'a3',
    userId: 'u1',
    quizId: 'q5',
    answers: { 'q5ques1': 0, 'q5ques2': 2, 'q5ques3': 2, 'q5ques4': 0, 'q5ques5': 1, 'q5ques6': 1, 'q5ques7': 2, 'q5ques8': 1 },
    score: 6,
    totalMarks: 8,
    percentage: 75,
    passed: true,
    timeTaken: 360,
    startedAt: '2025-04-10T09:00:00.000Z',
    submittedAt: '2025-04-10T09:06:00.000Z',
  },
  {
    id: 'a4',
    userId: 'u3',
    quizId: 'q1',
    answers: { 'q1ques1': 2, 'q1ques2': 2, 'q1ques3': 0, 'q1ques4': 0, 'q1ques5': 0, 'q1ques6': 1, 'q1ques7': 0, 'q1ques8': 0, 'q1ques9': 0, 'q1ques10': 3 },
    score: 5,
    totalMarks: 12,
    percentage: 42,
    passed: false,
    timeTaken: 720,
    startedAt: '2025-04-12T11:00:00.000Z',
    submittedAt: '2025-04-12T11:12:00.000Z',
  },
  {
    id: 'a5',
    userId: 'u3',
    quizId: 'q2',
    answers: { 'q2ques1': 0, 'q2ques2': 2, 'q2ques3': 1, 'q2ques4': 2, 'q2ques5': 1, 'q2ques6': 0, 'q2ques7': 0, 'q2ques8': 2, 'q2ques9': 0, 'q2ques10': 1 },
    score: 8,
    totalMarks: 10,
    percentage: 80,
    passed: true,
    timeTaken: 500,
    startedAt: '2025-04-14T15:00:00.000Z',
    submittedAt: '2025-04-14T15:08:20.000Z',
  },
  {
    id: 'a6',
    userId: 'u4',
    quizId: 'q1',
    answers: { 'q1ques1': 0, 'q1ques2': 0, 'q1ques3': 0, 'q1ques4': 1, 'q1ques5': 1, 'q1ques6': 1, 'q1ques7': 0, 'q1ques8': 1, 'q1ques9': 0, 'q1ques10': 3 },
    score: 5,
    totalMarks: 12,
    percentage: 42,
    passed: false,
    timeTaken: 900,
    startedAt: '2025-04-15T10:00:00.000Z',
    submittedAt: '2025-04-15T10:15:00.000Z',
  },
];

export function initializeData() {
  const existingUsers = Storage.get(KEYS.USERS);
  if (!existingUsers || existingUsers.length === 0) {
    Storage.set(KEYS.USERS, demoUsers);
  }
  const existingQuizzes = Storage.get(KEYS.QUIZZES);
  if (!existingQuizzes || existingQuizzes.length === 0) {
    Storage.set(KEYS.QUIZZES, demoQuizzes);
  }
  const existingAttempts = Storage.get(KEYS.ATTEMPTS);
  if (!existingAttempts || existingAttempts.length === 0) {
    Storage.set(KEYS.ATTEMPTS, demoAttempts);
  }
}
